server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;

  location = /up {
    access_log off;
    default_type text/plain;
    return 200 'ok';
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /favicon.ico {
    log_not_found off;
    access_log off;
  }
}
