services:
  api:
    image: ${IMAGE_ROOT}-api:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    networks:
      - relay_edge
      - relay_internal
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - traefik.enable=true
        - traefik.http.routers.${PROJECT}-api.rule=Host(`api.${CNAME}`)
        - traefik.http.routers.${PROJECT}-api.entrypoints=https
        - traefik.http.routers.${PROJECT}-api.tls=true
        - traefik.http.routers.${PROJECT}-api.tls.certresolver=letsencrypt
        - traefik.http.routers.${PROJECT}-api.service=${PROJECT}-api
        - traefik.http.services.${PROJECT}-api.loadbalancer.server.port=3000
        - traefik.http.services.${PROJECT}-api.loadbalancer.healthcheck.path=/up
        - traefik.http.services.${PROJECT}-api.loadbalancer.healthcheck.interval=5s
        - traefik.http.services.${PROJECT}-api.loadbalancer.healthcheck.timeout=2s
    healthcheck:
      test: [ 'CMD-SHELL', 'wget -qO- http://127.0.0.1:3000/up >/dev/null || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  relay_edge:
    external: true
  relay_internal:
    external: true
